# site settings
title: Kaitlin Throgmorton
subtitle: MLIS
email: kaitlin@kaitlinthrogmorton.com
description: From a love of literature, to a love of writing, to a love of data, my career journey has taken a few turns over the past decade. One theme weaves through it all, however: I love helping people access the information they need.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/kthrog
gitlab_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/kthrog/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/kthrog

# build settings
markdown: kramdown

sass:
  style: compressed
